services:
  - type: web
    name: rajjobs-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMS_ENABLED
        value: false
