const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const router = express.Router();

// ─── Cloudinary setup (used in production when env vars are set) ─────────────
let cloudinary = null;
const CLOUDINARY_CONFIGURED =
  process.env.CLOUDINARY_CLOUD_NAME &&
  process.env.CLOUDINARY_API_KEY &&
  process.env.CLOUDINARY_API_SECRET;

if (CLOUDINARY_CONFIGURED) {
  cloudinary = require('cloudinary').v2;
  cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key:    process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
  });
  console.log('☁️  Cloudinary PDF storage: ACTIVE');
} else {
  console.log('💾 Local PDF storage: ACTIVE (set CLOUDINARY_* env vars for cloud storage)');
}

// ─── Local storage (for local dev / fallback) ────────────────────────────────
const uploadsDir = path.join(__dirname, '../../../uploads/pdfs');
if (!fs.existsSync(uploadsDir)) {
  fs.mkdirSync(uploadsDir, { recursive: true });
}

const localStorage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadsDir),
  filename: (req, file, cb) => {
    const unique = Date.now() + '-' + Math.round(Math.random() * 1e9);
    cb(null, unique + '-' + file.originalname);
  },
});

// Use memory storage when Cloudinary is active (stream directly to cloud)
const multerStorage = CLOUDINARY_CONFIGURED
  ? multer.memoryStorage()
  : localStorage;

const fileFilter = (req, file, cb) => {
  if (file.mimetype === 'application/pdf') {
    cb(null, true);
  } else {
    cb(new Error('Only PDF files are allowed!'), false);
  }
};

const upload = multer({
  storage: multerStorage,
  fileFilter,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10 MB
});

// ─── Upload PDF endpoint ──────────────────────────────────────────────────────
router.post('/upload-pdf', upload.single('pdf'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, message: 'No file uploaded' });
    }

    let absoluteUrl;

    if (CLOUDINARY_CONFIGURED) {
      // ── Upload buffer to Cloudinary ──
      const uploadResult = await new Promise((resolve, reject) => {
        // Sanitize filename: remove extension, keep only alphanumeric, hyphens, and underscores
        const sanitizedName = req.file.originalname
          .replace(/\.[^/.]+$/, '')  // Remove extension
          .replace(/[^a-zA-Z0-9-_]/g, '_');  // Replace invalid chars with underscore
        
        const stream = cloudinary.uploader.upload_stream(
          {
            resource_type: 'raw',
            folder: 'rajjobs-pdfs',
            public_id: `${Date.now()}-${sanitizedName}`,
            format: 'pdf',
            use_filename: false,
            // Explicitly public so the signed URL generated by pdf-proxy works correctly
            type: 'upload',
            access_mode: 'public',
          },
          (error, result) => {
            if (error) reject(error);
            else resolve(result);
          }
        );
        stream.end(req.file.buffer);
      });
      absoluteUrl = uploadResult.secure_url; // permanent Cloudinary HTTPS URL
    } else {
      // ── Local storage: build absolute URL ──
      const relativeUrl = `/uploads/pdfs/${req.file.filename}`;
      const backendBase =
        process.env.BACKEND_URL ||
        `${req.protocol}://${req.get('host')}`;
      absoluteUrl = `${backendBase}${relativeUrl}`;
    }

    res.json({
      success: true,
      message: 'File uploaded successfully',
      data: {
        url: absoluteUrl,               // ← always an absolute URL
        originalName: req.file.originalname,
        size: req.file.size,
        storage: CLOUDINARY_CONFIGURED ? 'cloudinary' : 'local',
      },
    });
  } catch (error) {
    console.error('File upload error:', error);
    res.status(500).json({
      success: false,
      message: 'File upload failed',
      error: error.message,
    });
  }
});

// ─── Delete PDF endpoint ──────────────────────────────────────────────────────
router.delete('/delete-pdf/:filename', (req, res) => {
  try {
    const filename = req.params.filename;
    const filePath = path.join(uploadsDir, filename);

    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      res.json({ success: true, message: 'File deleted successfully' });
    } else {
      res.status(404).json({ success: false, message: 'File not found' });
    }
  } catch (error) {
    console.error('File deletion error:', error);
    res.status(500).json({
      success: false,
      message: 'File deletion failed',
      error: error.message,
    });
  }
});

module.exports = router;
