const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const router = express.Router();

// ─── Cloudinary setup (used in production when env vars are set) ─────────────
let cloudinary = null;
const CLOUDINARY_CONFIGURED =
  process.env.CLOUDINARY_CLOUD_NAME &&
  process.env.CLOUDINARY_API_KEY &&
  process.env.CLOUDINARY_API_SECRET;

if (CLOUDINARY_CONFIGURED) {
  cloudinary = require('cloudinary').v2;
  cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key:    process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
  });
  console.log('☁️  Cloudinary PDF storage: ACTIVE');
} else {
  console.log('💾 Local PDF storage: ACTIVE (set CLOUDINARY_* env vars for cloud storage)');
}

// ─── Local storage (for local dev / fallback) ────────────────────────────────
const uploadsDir = path.join(__dirname, '../../../uploads/pdfs');
if (!fs.existsSync(uploadsDir)) {
  fs.mkdirSync(uploadsDir, { recursive: true });
}

const localStorage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadsDir),
  filename: (req, file, cb) => {
    const unique = Date.now() + '-' + Math.round(Math.random() * 1e9);
    cb(null, unique + '-' + file.originalname);
  },
});

// Use memory storage when Cloudinary is active (stream directly to cloud)
// BUT we'll also save locally as fallback for pdf-proxy
const multerStorage = multer.memoryStorage();

const fileFilter = (req, file, cb) => {
  if (file.mimetype === 'application/pdf') {
    cb(null, true);
  } else {
    cb(new Error('Only PDF files are allowed!'), false);
  }
};

const upload = multer({
  storage: multerStorage,
  fileFilter,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10 MB
});

// ─── Upload PDF endpoint ──────────────────────────────────────────────────────
router.post('/upload-pdf', upload.single('pdf'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, message: 'No file uploaded' });
    }

    let absoluteUrl;
    let localFilename = null;

    // Generate unique local filename
    const localFileUnique = Date.now() + '-' + Math.round(Math.random() * 1e9);
    const localFileName = localFileUnique + '-' + req.file.originalname;
    const localFilePath = path.join(uploadsDir, localFileName);

    if (CLOUDINARY_CONFIGURED) {
      // ── Upload buffer to Cloudinary ──
      const uploadResult = await new Promise((resolve, reject) => {
        // Sanitize filename: remove extension, keep only alphanumeric, hyphens, and underscores
        const sanitizedName = req.file.originalname
          .replace(/\.[^/.]+$/, '')  // Remove extension
          .replace(/[^a-zA-Z0-9-_]/g, '_');  // Replace invalid chars with underscore
        
        const stream = cloudinary.uploader.upload_stream(
          {
            resource_type: 'raw',
            folder: 'rajjobs-pdfs',
            public_id: `${Date.now()}-${sanitizedName}`,
            format: 'pdf',
            use_filename: false,
            // Explicitly public so the signed URL generated by pdf-proxy works correctly
            type: 'upload',
            access_mode: 'public',
          },
          (error, result) => {
            if (error) reject(error);
            else resolve(result);
          }
        );
        stream.end(req.file.buffer);
      });

      absoluteUrl = uploadResult.secure_url; // permanent Cloudinary HTTPS URL

      // ✅ ALSO save locally as fallback for pdf-proxy
      try {
        fs.writeFileSync(localFilePath, req.file.buffer);
        localFilename = localFileName;
        console.log('✅ Saved backup copy locally:', localFileName);
      } catch (writeErr) {
        console.warn('⚠️  Failed to save local backup:', writeErr.message);
        // Don't fail the upload if local save fails - Cloudinary is primary
      }
    } else {
      // ── Local storage only ──
      fs.writeFileSync(localFilePath, req.file.buffer);
      localFilename = localFileName;
      
      const relativeUrl = `/uploads/pdfs/${localFileName}`;
      const backendBase =
        process.env.BACKEND_URL ||
        `${req.protocol}://${req.get('host')}`;
      absoluteUrl = `${backendBase}${relativeUrl}`;
    }

    res.json({
      success: true,
      message: 'File uploaded successfully',
      data: {
        url: absoluteUrl,               // ← Cloudinary URL (primary)
        localBackup: localFilename,     // ← Local filename (fallback)
        originalName: req.file.originalname,
        size: req.file.size,
        storage: CLOUDINARY_CONFIGURED ? 'cloudinary+local-backup' : 'local',
      },
    });
  } catch (error) {
    console.error('File upload error:', error);
    res.status(500).json({
      success: false,
      message: 'File upload failed',
      error: error.message,
    });
  }
});

// ─── Delete PDF endpoint ──────────────────────────────────────────────────────
router.delete('/delete-pdf/:filename', (req, res) => {
  try {
    const filename = req.params.filename;
    const filePath = path.join(uploadsDir, filename);

    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      res.json({ success: true, message: 'File deleted successfully' });
    } else {
      res.status(404).json({ success: false, message: 'File not found' });
    }
  } catch (error) {
    console.error('File deletion error:', error);
    res.status(500).json({
      success: false,
      message: 'File deletion failed',
      error: error.message,
    });
  }
});

// ─── Image upload for CKEditor (supports multiple image formats) ──────────────
const imageFilter = (req, file, cb) => {
  const allowedMimes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp'];
  if (allowedMimes.includes(file.mimetype)) {
    cb(null, true);
  } else {
    cb(new Error('Only JPEG, PNG, GIF, WebP, and BMP images are allowed!'), false);
  }
};

const imageUpload = multer({
  storage: multer.memoryStorage(),
  fileFilter: imageFilter,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5 MB for images
});

const imageDir = path.join(__dirname, '../../../uploads/images');
if (!fs.existsSync(imageDir)) {
  fs.mkdirSync(imageDir, { recursive: true });
}

router.post('/upload-image', imageUpload.single('upload'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        error: { message: 'No file uploaded' }
      });
    }

    let absoluteUrl;
    const imageFileUnique = Date.now() + '-' + Math.round(Math.random() * 1e9);
    const imageFileName = imageFileUnique + '-' + req.file.originalname;
    const imageFilePath = path.join(imageDir, imageFileName);

    if (CLOUDINARY_CONFIGURED) {
      // Upload to Cloudinary
      const uploadResult = await new Promise((resolve, reject) => {
        const sanitizedName = req.file.originalname
          .replace(/\.[^/.]+$/, '')
          .replace(/[^a-zA-Z0-9-_]/g, '_');
        
        const stream = cloudinary.uploader.upload_stream(
          {
            resource_type: 'image',
            folder: 'rajjobs-images',
            public_id: `${Date.now()}-${sanitizedName}`,
            use_filename: false,
            type: 'upload',
            access_mode: 'public',
          },
          (error, result) => {
            if (error) reject(error);
            else resolve(result);
          }
        );
        stream.end(req.file.buffer);
      });

      absoluteUrl = uploadResult.secure_url;

      // Save locally as fallback
      try {
        fs.writeFileSync(imageFilePath, req.file.buffer);
        console.log('✅ Image saved locally:', imageFileName);
      } catch (writeErr) {
        console.warn('⚠️  Failed to save local image backup:', writeErr.message);
      }
    } else {
      // Local storage only
      fs.writeFileSync(imageFilePath, req.file.buffer);
      const relativeUrl = `/uploads/images/${imageFileName}`;
      const backendBase = process.env.BACKEND_URL || `${req.protocol}://${req.get('host')}`;
      absoluteUrl = `${backendBase}${relativeUrl}`;
    }

    // CKEditor expects specific response format
    res.json({
      url: absoluteUrl
    });
  } catch (error) {
    console.error('❌ Image upload error:', error);
    res.status(500).json({
      error: { message: error.message || 'Image upload failed' }
    });
  }
});

module.exports = router;
